### ISSUE TITLE
Stuck on chrome home page

### ISSUE THREAD

**Issue by lsshepard** [makiisthenes/TiktokAutoUploader#18]
When I run the main script it opens an instance of the chrome browser, but stays stuck on the chrome home screen. I believe the problem has to do with line 26 and 27 in 'Video.py': 

        while not os.path.isfile(self.source_ref):
            time.sleep(1)

I don't really know what this does, or how to fix it. Any ideas?

I was also wondering what Im supposed to change the IMAGEMAGICK_BINARY path to. I have currently left it as 'auto-detect'.
Edit: I see that the file convert.exe is not used in the newest version of magic. Is there some way around this?

**Comment by fedecech** [comment]
Hey @lsshepard, sorry for the super late answer, but the repo is slowly starting to come back to life.

> When I run the main script it opens an instance of the chrome browser, but stays stuck on the chrome home screen. I believe the problem has to do with line 26 and 27 in 'Video.py'

I believe that could be caused by an invalid `source_ref` path. The code is still a bit janky there. I believe the purpose of the while loop is to wait that the file from YouTube is downloaded completely thus that it can be found in the filesystem. What could happens tho, and probably what is happening to you is that you are passing an invalid file path (`source_ref `). So it doesn't try to download anything from youtube, but it gets stuck in the loop as the file doesn't exist and will never exist.

I'd recommend you to double check for that.

Regarding `IMAGEMAGICK_BINARY `, I'm not 100% sure, I believe it is/was a problem only for Windows and that in macOS/linux it is autodetected. It could be the case that it got fixed also for Windows, but I don't use that OS, so can't be sure.

Hope this answers your question, and thanks for your interest :)
