### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by zhangrongwu** [makiisthenes/TiktokAutoUploader#30]
Major error, cannot find the file upload button, please update getVideoUploadInput() in Bot.py

**Comment by miraniskl** [comment]
I am having the same issue, not sure what to do. I looked on stack overflow and tried to find the element by XPath but it still doesn't work

**Comment by makiisthenes** [comment]
Hi @zhangrongwu and @miraniskl,

It seems that you are experiencing difficulty finding the file upload button in the Bot.py file. This issue may arise due to changes in the website elements or regional differences.

To address this, we have updated the code to rely on TikTok's API instead of web elements that are subject to frequent changes. This should help resolve the issue you are facing.

@miraniskl, with regards to:

> I ... tried to find the element by XPath but it still doesn't work

 I recommend giving the updated code a try and let us know if you are still experiencing issues.

Please feel free to reach out if you need further assistance.
