### ISSUE TITLE
Error for python cli.py login -n my_saved_username

### ISSUE THREAD

**Issue by turpez** [makiisthenes/TiktokAutoUploader#64]
![image](https://github.com/makiisthenes/TiktokAutoUploader/assets/29740508/0f7d619d-9950-4f11-b2e0-1b1721987364)

**Comment by eliktri23** [comment]
The problem is related to os.getenv("TIKTOK_LOGIN_URL"). The .env file is missing in the current release. Or replace this value with the text of the link https://www.tiktok.com/login /, lio create .env and add all of the config.txt 

When you log in to your account, there will still be problems with endless downloads. Here is a request for a solution to the problem(https://github.com/makiisthenes/TiktokAutoUploader/issues/63), and it has not been resolved yet

**Comment by turpez** [comment]
it does not work to put directly https://www.tiktok.com/login

![image](https://github.com/makiisthenes/TiktokAutoUploader/assets/29740508/40b4f018-a3c0-44f7-bb40-e5d5ffbe20e3)
